//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeawavesCompo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompoPack
    {
        public string Id { get; set; }
        public string CompetitionID { get; set; }
        public string Instructions { get; set; }
        public string CompoPackLink { get; set; }
        public Nullable<bool> isReleased { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual Competition Competition { get; set; }
    }
}
