//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeawavesCompo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competition()
        {
            this.Entries = new HashSet<Entry>();
            this.CompoPacks = new HashSet<CompoPack>();
        }
    
        public string Id { get; set; }
        public System.DateTime CompoLength { get; set; }
        public System.DateTime VoteLength { get; set; }
        public System.DateTime CompoStartDate { get; set; }
        public int CurrentPhase { get; set; }
        public string HostUserID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public string Title { get; set; }
        public int CompoType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entry> Entries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompoPack> CompoPacks { get; set; }
        public virtual User User { get; set; }
    }
}
