//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeawavesCompo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public string Id { get; set; }
        public string CompetitionID { get; set; }
        public string AuthorUserID { get; set; }
        public string TempURL { get; set; }
        public string PermanentURL { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> IsAnonymous { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<int> Score { get; set; }
        public string Title { get; set; }
    
        public virtual User User { get; set; }
        public virtual Competition Competition { get; set; }
    }
}
